sonar.organization=metratio
sonar.projectKey=metratio_attention-leverage
sonar.projectName=attention-leverage
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
